2022-06-09 01:11:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES(1, 'Kurt', 'Cobain', 20/02/1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22018-212]
2022-06-09 01:11:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES(2, 'Dave', 'Grohl', 14/01/1969, 'dave.grohl69@gmail.com', 'Gable Dr Encino', 172, 91316, 'A2') [22018-212]
2022-06-09 01:11:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES(3, 'Krist', 'Novoselic', 16/05/1965, 'krist.novo65@gmail.com', 'S Lucile St', 173, 98148, 'AM') [22018-212]
2022-06-09 01:13:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 20/02/1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22018-212]
2022-06-09 01:13:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 20/02/1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22018-212]
2022-06-09 01:13:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:13:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "-1949 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 20-02-1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22018-212]
2022-06-09 01:14:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 20/02/1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22018-212]
2022-06-09 01:15:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', 171, 98112, 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:15:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:15:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:15:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:15:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "DATE" constant "20/02/1967"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', '20/02/1967', 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22007-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueDate.parse(ValueDate.java:53)
	at org.h2.value.Value.convertToDate(Value.java:1854)
	at org.h2.value.Value.convertTo(Value.java:1147)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "20/02/"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:190)
	at org.h2.value.ValueDate.parse(ValueDate.java:51)
	... 19 more
2022-06-09 01:15:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "0 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 20/02/1967, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22018-212]
2022-06-09 01:16:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "TO_DATE" not found; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', TO_DATE('20/02/1967'), 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [90022-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readFunction(Parser.java:3894)
	at org.h2.command.Parser.readTerm(Parser.java:5227)
	at org.h2.command.Parser.readFactor(Parser.java:3440)
	at org.h2.command.Parser.readSum(Parser.java:3427)
	at org.h2.command.Parser.readConcat(Parser.java:3392)
	at org.h2.command.Parser.readCondition(Parser.java:3177)
	at org.h2.command.Parser.readExpression(Parser.java:3093)
	at org.h2.command.Parser.readExpressionOrDefault(Parser.java:3079)
	at org.h2.command.Parser.parseValuesForCommand(Parser.java:1800)
	at org.h2.command.Parser.parseInsert(Parser.java:1671)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-09 01:18:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "1945 (CLIENTE: ""DATANASCITA"" DATE)"; SQL statement:
INSERT INTO CLIENTE VALUES('AB345678', 'Kurt', 'Cobain', 1967-02-20, 'kurt.cobain67@gmail.com', 'Lake Washington Blvd', '171', '98112', 'A1') [22018-212]
2022-06-09 01:22:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'CD91234\\00a0\\00a0\\00a0' (10)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:22:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'CD91234\\00a0\\00a0\\00a0' (10)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:22:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF12345\\00a0\\00a0\\00a0\\00a0\\00a0' (12)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:22:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF12345\\00a0\\00a0\\00a0\\00a0\\00a0' (12)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:23:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF678912\\00a0\\00a0\\00a0' (11)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:23:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF678912\\00a0\\00a0\\00a0' (11)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:23:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF67891\\00a0\\00a0\\00a0\\00a0\\00a0' (12)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 01:23:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "NUMEROCARTA CHARACTER(8)": "U&'EF67891\\00a0\\00a0\\00a0\\00a0\\00a0' (12)"; SQL statement:
UPDATE "PUBLIC"."CLIENTE" SET "NUMEROCARTA"=? ,"NOME"=? ,"COGNOME"=? ,"DATANASCITA"=? ,"EMAIL"=? ,"VIA"=? ,"CIVICO"=? ,"CAP"=? ,"PATENTEDACONSEGUIRE"=?  WHERE "NUMEROCARTA"=? [22001-212]
2022-06-09 17:12:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException: Cannot invoke ""String.length()"" because ""<parameter1>"" is null" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.message.DbException.toSQLException(DbException.java:367)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:365)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:225)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
	at org.h2.util.ParserUtil.getTokenType(ParserUtil.java:680)
	at org.h2.util.ParserUtil.isKeyword(ParserUtil.java:622)
	at org.h2.command.Parser.isKeyword(Parser.java:5876)
	at org.h2.command.Parser.readIfDataType1(Parser.java:6079)
	at org.h2.command.Parser.readIfDataType(Parser.java:6040)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:6022)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5897)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:9328)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:8991)
	at org.h2.command.Parser.parseAlterTable(Parser.java:8461)
	at org.h2.command.Parser.parseAlter(Parser.java:7522)
	at org.h2.command.Parser.parsePrepared(Parser.java:747)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	... 7 more
2022-06-09 17:13:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE CLIENTE[*]"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
ALTER TABLE CLIENTE [42001-212]
2022-06-09 17:13:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE CLIENTE [*][USERNAME]"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
ALTER TABLE CLIENTE [USERNAME] [42001-212]
2022-06-09 17:14:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "USERNAME"; SQL statement:
ALTER TABLE CLIENTE ADD COLOUMN USERNAME [50004-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.readIfDataType1(Parser.java:6199)
	at org.h2.command.Parser.readIfDataType(Parser.java:6040)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:6022)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5897)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:9328)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:8991)
	at org.h2.command.Parser.parseAlterTable(Parser.java:8461)
	at org.h2.command.Parser.parseAlter(Parser.java:7522)
	at org.h2.command.Parser.parsePrepared(Parser.java:747)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-09 17:14:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException: Cannot invoke ""String.length()"" because ""<parameter1>"" is null" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.message.DbException.toSQLException(DbException.java:367)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:365)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:225)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
	at org.h2.util.ParserUtil.getTokenType(ParserUtil.java:680)
	at org.h2.util.ParserUtil.isKeyword(ParserUtil.java:622)
	at org.h2.command.Parser.isKeyword(Parser.java:5876)
	at org.h2.command.Parser.readIfDataType1(Parser.java:6079)
	at org.h2.command.Parser.readIfDataType(Parser.java:6040)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:6022)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5897)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:9328)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:8991)
	at org.h2.command.Parser.parseAlterTable(Parser.java:8461)
	at org.h2.command.Parser.parseAlter(Parser.java:7522)
	at org.h2.command.Parser.parsePrepared(Parser.java:747)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	... 7
2022-06-10 18:10:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]Istruttori (Matricola, nome, cognome, e-mail, telefono)\000d\000a\000d\000aCREATE TABLE ISTRUTTORI(\000d\000aMATRICOLA CHAR(4) NOT NULL PRIMARY KEY,\000d\000aNOME VARCHAR(20),\000d\000aCOGNOME VARCHAR(20),\000d\000aEMAIL VARCHAR(30),\000d\000aTELEFONO VARCHAR(10)"; expected "INSERT"; SQL statement:
Istruttori (Matricola, nome, cognome, e-mail, telefono)

CREATE TABLE ISTRUTTORI(
MATRICOLA CHAR(4) NOT NULL PRIMARY KEY,
NOME VARCHAR(20),
COGNOME VARCHAR(20),
EMAIL VARCHAR(30),
TELEFONO VARCHAR(10) [42001-212]
2022-06-10 18:10:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*])"; SQL statement:
) [42000-212]
2022-06-10 18:10:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ISTRUTTORI(\000d\000aMATRICOLA CHAR(4) NOT NULL PRIMARY KEY,\000d\000aNOME VARCHAR(20),\000d\000aCOGNOME VARCHAR(20),\000d\000aEMAIL VARCHAR(30),\000d\000aTELEFONO VARCHAR(10)[*]"; expected "ARRAY, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, DEFAULT, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE ISTRUTTORI(
MATRICOLA CHAR(4) NOT NULL PRIMARY KEY,
NOME VARCHAR(20),
COGNOME VARCHAR(20),
EMAIL VARCHAR(30),
TELEFONO VARCHAR(10) [42001-212]
2022-06-10 18:10:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*])"; SQL statement:
) [42000-212]
2022-06-10 18:10:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ISTRUTTORI(\000d\000aMATRICOLA CHAR(4) NOT NULL PRIMARY KEY,\000d\000aNOME VARCHAR(20),\000d\000aCOGNOME VARCHAR(20),\000d\000aEMAIL VARCHAR(30),\000d\000aTELEFONO VARCHAR(10)[*]"; expected "ARRAY, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, DEFAULT, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE ISTRUTTORI(
MATRICOLA CHAR(4) NOT NULL PRIMARY KEY,
NOME VARCHAR(20),
COGNOME VARCHAR(20),
EMAIL VARCHAR(30),
TELEFONO VARCHAR(10) [42001-212]
2022-06-10 18:10:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*])"; SQL statement:
) [42000-212]
2022-06-10 18:27:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Attempt to define a second primary key; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL PRIMARY KEY,
ORA CHAR(5) NOT NULL PRIMARY KEY,
ISTRUTTORE CHAR(4) NOT NULL PRIMARY KEY,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)) [90017-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.ddl.CommandWithColumns.setPrimaryKey(CommandWithColumns.java:148)
	at org.h2.command.ddl.CommandWithColumns.addConstraintCommand(CommandWithColumns.java:49)
	at org.h2.command.Parser.readColumnConstraints(Parser.java:9381)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:9333)
	at org.h2.command.Parser.parseCreateTable(Parser.java:9266)
	at org.h2.command.Parser.parseCreate(Parser.java:6745)
	at org.h2.command.Parser.parsePrepared(Parser.java:763)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 18:31:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL PRIMARY KEY,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aFOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000a[*]CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA))"; expected "INDEX, ON, NOT, DEFERRABLE, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL PRIMARY KEY,
ISTRUTTORE CHAR(4) NOT NULL,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)) [42001-212]
2022-06-10 18:32:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL ,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aFOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000a[*]CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA))"; expected "INDEX, ON, NOT, DEFERRABLE, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL ,
ISTRUTTORE CHAR(4) NOT NULL,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)) [42001-212]
2022-06-10 18:32:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL ,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aFOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000a[*]CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA))"; expected "INDEX, ON, NOT, DEFERRABLE, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL ,
ISTRUTTORE CHAR(4) NOT NULL,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)) [42001-212]
2022-06-10 18:32:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL ,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aFOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000a[*]CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA))"; expected "INDEX, ON, NOT, DEFERRABLE, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL ,
ISTRUTTORE CHAR(4) NOT NULL,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)) [42001-212]
2022-06-10 18:33:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL ,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA))"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL ,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)) [42001-212]
2022-06-10 18:39:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL ,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL ,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA)
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:41:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),
) [42001-212]
2022-06-10 18:41:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),
) [42001-212]
2022-06-10 18:42:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),
) [42001-212]
2022-06-10 18:43:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),
) [42001-212]
2022-06-10 18:43:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA),
) [42001-212]
2022-06-10 18:45:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:45:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:46:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:46:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 18:46:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE DISPONIBILITA(\000d\000aGIORNO VARCHAR(9) NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCONSTRAINT [*]FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aCONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)\000d\000a)"; expected "identifier"; SQL statement:
CREATE TABLE DISPONIBILITA(
GIORNO VARCHAR(9) NOT NULL,
ORA CHAR(5) NOT NULL,
ISTRUTTORE CHAR(4) NOT NULL,
CONSTRAINT FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
CONSTRAINT pk_disponibilita PRIMARY KEY(ISTRUTTORE, GIORNO, ORA)
) [42001-212]
2022-06-10 19:08:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE [*]LEZIONIGUIDA(\000d\000aIDLEZIONE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,\000d\000aDATA DATE NOT NULL,\000d\000aORA CHAR(5) NOT NULL,\000d\000aDURATA  INT,\000d\000aTIPOPATENTE VARCHAR(4),\000d\000aISTRUTTORE CHAR(4) NOT NULL,\000d\000aCLIENTE CHAR(9) NOT NULL,\000d\000aFOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),\000d\000aFOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID)\000d\000a)"; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE LEZIONIGUIDA(
IDLEZIONE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATA DATE NOT NULL,
ORA CHAR(5) NOT NULL,
DURATA  INT,
TIPOPATENTE VARCHAR(4),
ISTRUTTORE CHAR(4) NOT NULL,
CLIENTE CHAR(9) NOT NULL,
FOREIGN KEY (ISTRUTTORE) REFERENCES ISTRUTTORI(MATRICOLA),
FOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID)
) [42001-212]
2022-06-10 19:18:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TIPOPATENTE" not found; SQL statement:
CREATE TABLE ISCRIZIONI(
CLIENTE CHAR(9) NOT NULL,
CORSO VARCHAR(4) NOT NULL,
DATAISCRIZIONE DATE,
DATACONSEGUIMENTO DATE DEFAULT NULL,
CONSTRAINT pk_iscrizioni PRIMARY KEY (CLIENTE, CORSO),
FOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID),
FOREIGN KEY (CORSO) REFERENCES TIPOPATENTE(CORSO)
) [42102-212]
2022-06-10 19:18:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CORSO" not found; SQL statement:
CREATE TABLE ISCRIZIONI(
CLIENTE CHAR(9) NOT NULL,
CORSO VARCHAR(4) NOT NULL,
DATAISCRIZIONE DATE,
DATACONSEGUIMENTO DATE DEFAULT NULL,
CONSTRAINT pk_iscrizioni PRIMARY KEY (CLIENTE, CORSO),
FOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID),
FOREIGN KEY (CORSO) REFERENCES CORSO(TIPOPATENTE)
) [42102-212]
2022-06-10 19:32:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "V" not found; SQL statement:
CREATE TABLE DOMANDE(
IDDOMANDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIGURA VARCHAR(40) DEFAULT NULL,
TEMA VARCHAR(20) NOT NULL,
FORMULAZIONE VARCHAR(100) NOT NULL,
RISPOSTACORRETTA CHAR(1) NOT NULL CHECK(RISPOSTACORRETTA=V OR RISPOSTACORRETTA=F)
) [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:140)
	at org.h2.expression.condition.ConditionAndOr.optimize(ConditionAndOr.java:136)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:191)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:131)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 19:32:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "V" not found; SQL statement:
CREATE TABLE DOMANDE(
IDDOMANDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIGURA VARCHAR(40) DEFAULT NULL,
TEMA VARCHAR(20) NOT NULL,
FORMULAZIONE VARCHAR(100) NOT NULL,
RISPOSTACORRETTA CHAR(1) NOT NULL CHECK(RISPOSTACORRETTA="V" OR RISPOSTACORRETTA="F")
) [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:140)
	at org.h2.expression.condition.ConditionAndOr.optimize(ConditionAndOr.java:136)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:191)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:131)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 19:36:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot drop "CORSI" because "CONSTRAINT_5E77" depends on it; SQL statement:
DROP TABLE CORSI [90107-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:97)
	at org.h2.command.ddl.DropTable.update(DropTable.java:121)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 19:36:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE CORSI(\000d\000aTIPOPATENTE VARCHAR(4) NOT NULL PRIMARY KEY,\000d\000aCONSTRAINT check_patente CHECK(TIPOPATENTE IN(""A1"", ""A2"", ""AM"", 'A', 'B')\000d\000a)[*]"; expected "., [, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE CORSI(
TIPOPATENTE VARCHAR(4) NOT NULL PRIMARY KEY,
CONSTRAINT check_patente CHECK(TIPOPATENTE IN("A1", "A2", "AM", 'A', 'B')
) [42001-212]
2022-06-10 19:37:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE CORSI(\000d\000aTIPOPATENTE VARCHAR(4) NOT NULL PRIMARY KEY,\000d\000aCONSTRAINT check_patente CHECK(TIPOPATENTE IN('A1', 'A2', 'AM', 'A', 'B')\000d\000a)[*]"; expected "., [, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, NOCHECK, CHECK, ,, )"; SQL statement:
CREATE TABLE CORSI(
TIPOPATENTE VARCHAR(4) NOT NULL PRIMARY KEY,
CONSTRAINT check_patente CHECK(TIPOPATENTE IN('A1', 'A2', 'AM', 'A', 'B')
) [42001-212]
2022-06-10 19:37:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CORSI" already exists; SQL statement:
CREATE TABLE CORSI(
TIPOPATENTE VARCHAR(2) NOT NULL PRIMARY KEY,
CONSTRAINT check_patente CHECK(TIPOPATENTE IN('A1', 'A2', 'AM', 'A', 'B'))
) [42101-212]
2022-06-10 19:37:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CORSI" already exists; SQL statement:
CREATE TABLE CORSI(
TIPOPATENTE VARCHAR(4) NOT NULL PRIMARY KEY,
CONSTRAINT check_patente CHECK(TIPOPATENTE IN('A1', 'A2', 'AM', 'A', 'B'))
) [42101-212]
2022-06-10 19:42:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE PROVE(\000d\000aIDPROVA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,\000d\000aCLIENTE CHAR(9) NOT NULL,\000d\000aDATA DATE NOT NULL,\000d\000aESITO CHAR(1) NOT NULL,\000d\000aCONSTRAINT check_esito CHECK(ESITO IN('p', 'P', 'n', 'N'),\000d\000a[*]FOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID)\000d\000a)"; expected "INTERSECTS, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
CREATE TABLE PROVE(
IDPROVA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CLIENTE CHAR(9) NOT NULL,
DATA DATE NOT NULL,
ESITO CHAR(1) NOT NULL,
CONSTRAINT check_esito CHECK(ESITO IN('p', 'P', 'n', 'N'),
FOREIGN KEY (CLIENTE) REFERENCES CLIENTI(CARTAID)
) [42001-212]
2022-06-10 19:53:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "FORMULAZIONE CHARACTER VARYING(100)": "U&'Ai passaggi a livello occorre usare la massima prudenza e moderare la velocit... (166)"; SQL statement:
INSERT INTO DOMANDE VALUES(1, NULL, 'Limiti di velocità', 'Ai passaggi a livello occorre usare la massima prudenza e moderare la velocità, per evitare situazioni di pericolo che comportino il danneggiamento delle attrezzature', 'v') [22001-212]
2022-06-10 19:53:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot drop "DOMANDE" because "CONSTRAINT_7C" depends on it; SQL statement:
DROP TABLE DOMANDE [90107-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:97)
	at org.h2.command.ddl.DropTable.update(DropTable.java:121)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 19:53:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot drop "PROVE" because "CONSTRAINT_7" depends on it; SQL statement:
DROP TABLE PROVE [90107-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:97)
	at org.h2.command.ddl.DropTable.update(DropTable.java:121)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-10 20:03:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO DOMANDE VALUES(2, NULL, 'Limiti di velocità', 'E' obbligatorio regolare la velocità nelle ore diurne ma non in quelle notturne', 'f[*]')"; SQL statement:
INSERT INTO DOMANDE VALUES(2, NULL, 'Limiti di velocità', 'E' obbligatorio regolare la velocità nelle ore diurne ma non in quelle notturne', 'f') [42000-212]
2022-06-12 00:38:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENTE" not found; SQL statement:
select * from cliente [42102-212]
2022-06-11 23:46:12 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-11 23:46:18 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-11 23:53:28 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-12 01:56:29 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at Database.DBManager.getConnection(DBManager.java:17)
	at Database.ClienteDAO.selectClienti(ClienteDAO.java:114)
	at Controller.GestioneScuolaGuida.selectClienti(GestioneScuolaGuida.java:78)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:29)
	at Boundary.MainMenu.main(MainMenu.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 01:57:03 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at Database.DBManager.getConnection(DBManager.java:17)
	at Database.ClienteDAO.selectClienti(ClienteDAO.java:114)
	at Controller.GestioneScuolaGuida.selectClienti(GestioneScuolaGuida.java:78)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:29)
	at Boundary.MainMenu.main(MainMenu.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 01:57:29 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at Database.DBManager.getConnection(DBManager.java:17)
	at Database.ClienteDAO.selectClienti(ClienteDAO.java:114)
	at Controller.GestioneScuolaGuida.selectClienti(GestioneScuolaGuida.java:78)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:29)
	at Boundary.MainMenu.main(MainMenu.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 02:03:40 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at Database.DBManager.getConnection(DBManager.java:17)
	at Database.ClienteDAO.selectClienti(ClienteDAO.java:114)
	at Controller.GestioneScuolaGuida.selectClienti(GestioneScuolaGuida.java:78)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:29)
	at Boundary.MainMenu.main(MainMenu.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 02:04:50 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:288)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:808)
	at org.h2.server.web.WebApp.login(WebApp.java:1033)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:153)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 02:04:58 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:288)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:808)
	at org.h2.server.web.WebApp.login(WebApp.java:1033)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:153)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 02:14:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (? [*]? ? ? ? ? ? ? ? ?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO CLIENTI VALUES (? ? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 00:16:19 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-12 00:27:26 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-12 02:47:59 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:124)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3349)
	at org.h2.mvstore.MVStore.panic(MVStore.java:590)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:466)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4118)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at Database.DBManager.getConnection(DBManager.java:17)
	at Database.ClienteDAO.memorizzaCliente(ClienteDAO.java:79)
	at Controller.GestioneScuolaGuida.memorizzaCliente(GestioneScuolaGuida.java:68)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:79)
	at Boundary.MainMenu.main(MainMenu.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]" [50000-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/claudio/GitHub/Java/canale_j_z-nirvana/ScuolaGuidaNirvana/lib/database.mv.db [2.1.212/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:449)
	... 16 more
2022-06-12 02:49:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (? [*]? ? ? ? ? ? ? ? ?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO CLIENTI VALUES (? ? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 02:51:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (? [[*]*]? ? ? ? ? ? ? ? ?);"; expected "INTERSECTS, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
INSERT INTO CLIENTI VALUES (? [*]? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 02:55:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (? [*]UNIQUE ? ? ? ? ? ? ? ? ?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO CLIENTI VALUES (? UNIQUE ? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 02:58:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI (CARTAID, NOME, COGNOME, DATANASCITA, EMAIL, VIA, NUMEROCIVICO, CAP) VALUES (? [*]UNIQUE ? ? ? ? ? ? ? ? ?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO CLIENTI (CARTAID, NOME, COGNOME, DATANASCITA, EMAIL, VIA, NUMEROCIVICO, CAP) VALUES (? UNIQUE ? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 03:04:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (UNIQUE [*]? ? ? ? ? ? ? ? ? ?);"; expected "("; SQL statement:
INSERT INTO CLIENTI VALUES (UNIQUE ? ? ? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 03:08:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (? [*]? ? ? ? ? ? ?);"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, NOT, IS, ILIKE, REGEXP, AND, OR, ,, )"; SQL statement:
INSERT INTO CLIENTI VALUES (? ? ? ? ? ? ? ?); [42001-212]
2022-06-12 03:10:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES (UNIQUE([*]?) ? ? ? ? ? ? ?);"; expected "WITH, (, SELECT, TABLE, VALUES"; SQL statement:
INSERT INTO CLIENTI VALUES (UNIQUE(?) ? ? ? ? ? ? ?); [42001-212]
2022-06-12 03:16:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, 55555, 'marcello55', '5marcelloPosix5[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, 55555, 'marcello55', '5marcelloPosix5'); [42000-212]
2022-06-12 03:16:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, 55555, 'marcello55', 'marcelloPosix5[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, 55555, 'marcello55', 'marcelloPosix5'); [42000-212]
2022-06-12 03:16:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, '55555', 'marcello55', 'marcelloPosix5[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', 5, '55555', 'marcello55', 'marcelloPosix5'); [42000-212]
2022-06-12 03:17:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix5[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix5'); [42000-212]
2022-06-12 03:17:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:18:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:18:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:18:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:18:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:18:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55'); [42000-212]
2022-06-12 03:19:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555'); [42000-212]
2022-06-12 03:19:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5'); [42000-212]
2022-06-12 03:19:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria'); [42000-212]
2022-06-12 03:19:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it'); [42000-212]
2022-06-12 03:19:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02'); [42000-212]
2022-06-12 03:19:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque'); [42000-212]
2022-06-12 03:19:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello'); [42000-212]
2022-06-12 03:19:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES([*]'MC5555555);"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555); [42000-212]
2022-06-12 03:19:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column count does not match; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555') [21002-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:295)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:574)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-12 03:20:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix[*]');"; SQL statement:
INSERT INTO CLIENTI VALUES('MC5555555, 'Marcello', 'Cinque', '1998-09-02', 'cinque@unina.it', 'Lago Patria', '5', '55555', 'marcello55', 'marcelloPosix'); [42000-212]
2022-06-12 03:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column count does not match; SQL statement:
INSERT INTO CLIENTI VALUES (?, ?, ?, ?, ?, ?, ?, ?); [21002-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:295)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:574)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at Database.ClienteDAO.memorizzaCliente(ClienteDAO.java:82)
	at Controller.GestioneScuolaGuida.memorizzaCliente(GestioneScuolaGuida.java:68)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:79)
	at Boundary.MainMenu.main(MainMenu.java:26)
2022-06-12 03:25:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "DATANASCINA" not found; SQL statement:
INSERT INTO CLIENTI (CARTAID, NOME, COGNOME, DATANASCINA, EMAIL, VIA, NUMEROCIVICO, CAP) VALUES (?, ?, ?, ?, ?, ?, ?, ?); [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:754)
	at org.h2.command.Parser.parseColumn(Parser.java:1264)
	at org.h2.command.Parser.parseColumnList(Parser.java:1249)
	at org.h2.command.Parser.parseInsert(Parser.java:1650)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:691)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:568)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at Database.ClienteDAO.memorizzaCliente(ClienteDAO.java:82)
	at Controller.GestioneScuolaGuida.memorizzaCliente(GestioneScuolaGuida.java:68)
	at Boundary.BoundarySegretario.registraCliente(BoundarySegretario.java:79)
	at Boundary.MainMenu.main(MainMenu.java:26)
2022-06-12 03:26:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "EMAIL CHARACTER VARYING(20)": "'kurt.cobain@nirvanamail.com' (27)"; SQL statement:
INSERT INTO CLIENTI (CARTAID, NOME, COGNOME, DATANASCITA, EMAIL, VIA, NUMEROCIVICO, CAP) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [22001-212]
2022-06-12 03:28:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "EMAIL CHARACTER VARYING(20)": "'kurt.cobain@nirvana.com' (23)"; SQL statement:
INSERT INTO CLIENTI (CARTAID, NOME, COGNOME, DATANASCITA, EMAIL, VIA, NUMEROCIVICO, CAP) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [22001-212]
2022-06-12 03:41:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TIPOPATENTE CHARACTER VARYING(4)": "'nessuna' (7)"; SQL statement:
INSERT INTO PATENTIINPOSSESSO VALUES (?, ?, ?) [22001-212]
2022-06-12 03:49:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENTE" not found; SQL statement:
delete from cliente where cartaid = 'AX5059049' [42102-212]
2022-06-12 03:49:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENTE" not found; SQL statement:
delete from cliente where cartaid = 'AX5059049' [42102-212]
2022-06-12 03:49:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENTE" not found; SQL statement:
delete from cliente where cartaid = 'AX5059049' [42102-212]
2022-06-12 03:59:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select * from clienti [*]and patentiinpossesso"; SQL statement:
select * from clienti and patentiinpossesso [42000-212]
2022-06-12 03:59:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select * from clienti [*]and patentiinpossesso"; SQL statement:
select * from clienti and patentiinpossesso [42000-212]
2022-06-12 17:29:08 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-12 17:48:35 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
